### ISSUE TITLE
Failed to build/compile on Oracle Linux 1.0 ( Sparc64 )

### ISSUE THREAD

**Issue by unixpro1970** [metalefty/X11RDP-RH-Matic#16]
The following errors cause my compile and rpmbuilds to fail on Oracle Linux 1.0 (Sparc64) 

--------------------------
Building xrdp... 

Oops, something going wrong around line: 254
See logs to get further information:
/tmp/tmp.HFHPIuUKT2.X11RDP-RH-Matic/build.log

gcc -DHAVE_CONFIG_H -I. -I../.. -I../../common    -DXRDP_CFG_PATH=\"/etc/xrdp\"  
-DXRDP_SBIN_PATH=\"/usr/sbin\" -DXRDP_SHARE_PATH=\"/usr/share/xrdp\" -DXRDP_PID__
PATH=\"/var/run\" -DXRDP_FUSE -O2 -g -m64 -mtune=ultrasparc -MT chansrv_fuse.o --
MD -MP -MF .deps/chansrv_fuse.Tpo -c -o chansrv_fuse.o chansrv_fuse.c
chansrv_fuse.c: In function 'xfuse_check_wait_objs':
chansrv_fuse.c:572: error: too few arguments to function 'fuse_session_process'
chansrv_fuse.c: In function 'xfuse_init_lib':
chansrv_fuse.c:806: error: too few arguments to function 'fuse_parse_cmdline'
make[3]: *** [chansrv_fuse.o] Error 1
-----------------------------------

However, I managed to address the compile issue by doing the following.  Is it possible to add the 5th arg numa support so others will not have this problem?

In rpmbuild/BUILD/neutrinolabs-xrdp-ee89984/sesman/chansrv/chansrv_fuse.c:

A) function: xfuse_check_wait_objs() 

Note: fuse_session_process takes 5 args but only 4 are specified. The 5th argument is related to a numa mount option. I believe 0 disables the numa mount but it might be a good idea to check if fuse_session_process takes 4 or 5 args for other architectures such as intel ( in the future ).

My temp hack is:

Changed:
#ifdef HACK
        fuse_session_process(g_se, buf, rval, tmpch);
#else
        fuse_session_process(g_se, g_buffer, rval, tmpch);
#endif

To:
#ifdef HACK
        fuse_session_process(g_se, buf, rval, tmpch, 0);
#else
        fuse_session_process(g_se, g_buffer, rval, tmpch, 0);
#endif
 
B) function xfuse_init_lib()

Note: fuse_parse_cmdline takes 5 args but only 4 are specified. The 5th argument is related to a numa mount option. I believe 0 disables the numa mount but it might be a good idea to check if fuse_parse_cmdline takes 4 or 5 args for other architectures such as intel ( in the future ).

My temp hack is:

Changed:
   if (fuse_parse_cmdline(args, &g_mount_point, 0, 0) < 0)
    {
        log_error("fuse_parse_cmdline() failed");
        fuse_opt_free_args(args);
        return -1;
    }

To:
   if (fuse_parse_cmdline(args, &g_mount_point, 0, 0, 0) < 0)
    {
        log_error("fuse_parse_cmdline() failed");
        fuse_opt_free_args(args);
        return -1;
    }

C) How can I restart the compile and rpm build from scratch without losing my changes (listed above)?   X11RDP-RH-Matic.sh will overwrite my modifications when I rerun the script.

**Comment by metalefty** [comment]
To keep your modifications, try this workaround.

1. make a patch of your change like `SOURCES/xrdp-pam-auth.patch`
2. put the patch file in `SOURCES` directory
3. edit `X11RDP-RH-Matic.sh`, add your patches to `EXTRA_SOURCE` variable
4. edit `SPECS/xrdp.spec.in`
  * add `Patch2: yourchanges.patch` below the line of `Patch1`
  * add `%patch2` below the line of `%patch1 -p 1`
5. rerun `X11RDP-RH-Matic.sh` script

However, this should be fixed in upstream. I'll report upstream developers this issue.

**Comment by metalefty** [comment]
Can you tell me the version of fuse-devel?
It seems Oracle Linux 1.0 does not exist.  What is correct version?

**Comment by metalefty** [comment]
Ah, I understand. Linux for sparc64 architecture, the version have 1.0.
https://oss.oracle.com/projects/linux-sparc/

**Comment by unixpro1970** [comment]
Yes, correct.

**Comment by unixpro1970** [comment]
The fuse-devel version is v2.8.

From:  metalefty <notifications@github.com>
Reply-To:  metalefty/X11RDP-RH-Matic
<reply+00f65dc2f5833b9f6784b9ebf6c06d0a999514e6fc11dc0b92cf00000001127900a69
2a169ce072c239e@reply.github.com>
Date:  Thursday, December 3, 2015 at 11:20 PM
To:  metalefty/X11RDP-RH-Matic <X11RDP-RH-Matic@noreply.github.com>
Cc:  Tony Rodriguez <unixpro1970@gmail.com>
Subject:  Re: [X11RDP-RH-Matic] Failed to build/compile on Oracle Linux 1.0
( Sparc64 ) based on Centos 6.5 (#16)


Can you tell me the version of fuse-devel?
It seems Oracle Linux 1.0 does not exist.  What is correct version?


Reply to this email directly or view it on GitHub
<https://github.com/metalefty/X11RDP-RH-Matic/issues/16#issuecomment-1618967
77> .

**Comment by metalefty** [comment]
Please try fuse-numa-sparc64 branch. 61d7173 is a workaround.
You can apply your modifications like this.

**Comment by metalefty** [comment]
The numa patch for fuse seems to be not merged into upstream now.
http://sourceforge.net/p/fuse/fuse/ci/master/tree/

I think it's too early to handle 4 args or 5 args in X11RDP-RH-Matic or xrdp upstream.
Very few Linux distributions use numa patched fuse.  If numa patches are merged into
fuse upstream and fuse with numa support become widely used, then we should fix it.
